### PR TITLE
Use Set for nub ord

### PR DESCRIPTION
**Pull request by MonoidMusician**
I haven't tested it yet but I'm pretty sure it works … I made separate commits to make it easy to follow but feel free to squash of course!

### CODE REVIEW

**Comment by milesfrain** [comment]
@MonoidMusician, Thanks for the help with this.

I'll definitely incorporate your set-based approach for lazy lists.
I want to do some more benchmarking to determine if this is the best approach for strict lists though (even though I appreciate the compact code).

Here's some initial benchmarking results on each branch:
https://github.com/milesfrain/purescript-lists/blob/nub-ord-bench/ord-bench.txt
https://github.com/milesfrain/purescript-lists/blob/nub-ord-set-bench/ord-set-bench.txt

Turns out neither version is stack safe. The original sorting approach fails at 100k elements, and this set approach fails at 10k elements. The sorting version is also noticeably faster after 100 elements. These results are highly-dependent on the number of duplicates though, and I suspect the set-based algo will outperform sorting if there's a high percentage of duplicates. We can more carefully control the distribution of duplicates with something like [arrayGen](https://github.com/JordanMartinez/purescript-arrays/blob/d5ad1de4bbe26cccbe04d8e47253f5c91267e3d6/bench/Data/Array.purs#L17-L18) (proposed in [another benchmarking PR](https://github.com/JordanMartinez/purescript-arrays/pull/1)).

My next step is going to be making the sorting version stack safe.

**Edit:** I wonder if there's any value in writing a more optimized variant of [List.sortBy](https://pursuit.purescript.org/packages/purescript-lists/5.4.1/docs/Data.List#v:sortBy) (e.g. `collapseSortBy`) that also lets you provide a "collapsing" function that decides which element to keep if the comparison function returns `EQ`. This would also probably only be useful in situations with lots of duplicates, which is also where the set-based approach shines too.

**Comment by milesfrain** [comment]
Working on stack safety in this other branch. https://github.com/milesfrain/purescript-lists/pull/2
Pretty confused why the composition of seemingly-stack-safe functions becomes not stack safe anymore. Do I need to use lists larger than 100k elements?

**Edit:** Turns out this is a problem with `sortBy`. Reported in https://github.com/purescript/purescript-lists/issues/192

**Comment by MonoidMusician** [comment]
Ah yeah, I’m glad you’re benchmarking it. I realized it wasn’t stack safe, but I saw that `nubEq` wasn’t either so I wasn’t sure if we needed that.

It’s interesting that the sorting would be faster, it seems like that does a lot more work but idk.

**Comment by milesfrain** [comment]
I incorporated your changes into https://github.com/purescript/purescript-lists/pull/179.
Once we address some of the other stack safety issues in the library, I'd like to do some more benchmarking.
Let me know if you have any ideas for making lazy `nub` stack-safe.

**Pull request closed without merging**
